name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Pre-build & Generate Plugin Configs
        run: |
          # এই কমান্ডগুলো গিটহাব রানারকে বাধ্য করবে প্লাগইনগুলো অ্যান্ড্রোয়েডের সাথে লিঙ্ক করাতে
          flutter precache --android
          flutter build apk --config-only

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: legal-vanguard-app
          path: build/app/outputs/flutter-apk/app-release.apk
          
